### PR TITLE
Export arrayBufferToBinaryString and binaryStringToArrayBuffer

### PR DESCRIPTION
**Pull request by josephfrazier**
I didn't add tests because the other tests implicitly test these
functions. Let me know if you'd like me to add explicit tests.

Best viewed ignoring whitespace changes: https://github.com/nolanlawson/blob-util/pull/43/files?w=1

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thank you very much for the PR @josephfrazier. Any functions that are exported should also ideally be documented. I need to update the process of building the documentation though because right now it's a bit manual. I'll tinker with this a bit and then merge because I see no reason not to expose these. :)

**Comment by josephfrazier** [comment]
Thanks, I had completely overlooked the docs! Let me know if there's anything else I can do to help.

**Comment by nolanlawson** [comment]
No prob, this project was due for some housekeeping anyway. :) I'm about to release a 2.0.0 that should expose these functions, please let me know if anything is amiss!

Closing because this should be resolved in #49, thanks again for the PR!

**Comment by josephfrazier** [comment]
Cheers, v2 is a huge improvement!

**Pull request closed without merging**
